export const REQUEST_FAIL = 'REQUEST_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const SET_LOADING = 'SET_LOADING';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const GET_ALL_PROVINCE = 'GET_ALL_PROVINCE';
export const CREATE_PROVINCE = 'CREATE_PROVINCE';
export const EDIT_PROVINCE = 'EDIT_PROVINCE';
export const DELETE_PROVINCE = 'DELETE_PROVINCE';

export const GET_ALL_METROS = 'GET_ALL_METROS';
export const CREATE_METRO = 'CREATE_METRO';
export const EDIT_METRO = 'EDIT_METRO';
export const DELETE_METRO = 'DELETE_METRO';

export const GET_ALL_DISTRICTS = 'GET_ALL_DISTRICTS';
export const CREATE_DISTRICT = 'CREATE_DISTRICT';
export const EDIT_DISTRICT = 'EDIT_DISTRICT';
export const DELETE_DISTRICT = 'DELETE_DISTRICT';

export const GET_ALL_WARDS = 'GET_ALL_WARDS';
export const CREATE_WARDS = 'CREATE_WARDS';
export const EDIT_WARDS = 'EDIT_WARDS';
export const DELETE_WARDS = 'DELETE_WARD';

export const GET_ALL_AREAS = 'GET_ALL_AREAS';
export const CREATE_AREA = 'CREATE_AREA';
export const EDIT_AREA = 'EDIT_AREA';
export const DELETE_AREA = 'DELETE_AREA';

export const GET_ALL_CBOS = 'GET_ALL_CBOS';
export const GET_CBO_BY_ID = 'GET_CBO_BY_ID';
export const CREATE_CBO = 'CREATE_CBO';
export const EDIT_CBO = 'EDIT_CBO';
export const DELETE_CBO = 'DELETE_CBO';

export const GET_ALL_BENEFICIARY = 'GET_ALL_BENEFICIARY';
export const CREATE_BENEFICIARY = 'CREATE_BENEFICIARY';
export const EDIT_BENEFICIARY = 'EDIT_BENEFICIARY';
export const DELETE_BENEFICIARY = 'DELETE_BENEFICIARY';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

